version: '2'
services:
    modifyfiled-app:
        image: modifyfiled
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://modifyfiled-mysql:3306/modifyfiled?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    modifyfiled-mysql:
        extends:
            file: mysql.yml
            service: modifyfiled-mysql
